version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'your_db'
      POSTGRES_USER: 'your_db_user'
      POSTGRES_PASSWORD: 'your_user_password'
    ports:
      - "5432:5432"
    networks:
      - backend

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge
