# Generated by Django 5.0.4 on 2024-04-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='user-e1839d7dd3', editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
