# Generated by Django 5.0.4 on 2024-04-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='user-a8c0d874a7', editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
