# Generated by Django 5.0.4 on 2024-05-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_managers_user_date_joined_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='user-fb8bc4c74d', editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
