# Generated by Django 5.0.4 on 2024-05-03 05:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_date_joined_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='user-83e8543337', editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
