# Generated by Django 5.0.4 on 2024-04-24 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.CharField(default='task-04531b8799', editable=False, max_length=15, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('content', models.TextField(blank=True, verbose_name='Contenido')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'In Progress'), (3, 'Done')], default=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Creado por')),
            ],
        ),
    ]
