# Generated by Django 5.0.4 on 2024-04-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='id',
            field=models.CharField(default='task-352ae638b2', editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
