# Generated by Django 5.0.4 on 2024-04-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_options_alter_tasks_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='id',
            field=models.CharField(default='task-27b32656a1', editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
