# Generated by Django 5.0.4 on 2024-04-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasks_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='id',
            field=models.CharField(default='task-8e6f9b683b', editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
