# Generated by Django 5.0.4 on 2024-05-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasks_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='id',
            field=models.CharField(default='task-40a6b87e6d', editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
